import type { Metadata } from "next";
import Header from "@/components/Header";
import "@/app/globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  dashboard,
  team,
}: Readonly<{ children: React.ReactNode; dashboard: React.ReactNode; team: React.ReactNode }>) {
  return (
    <html lang="en">
      <body className=" bg-gray-800 h-screen">
        <Header></Header>
        <section className=" my-4">{children}</section>
        <section className=" my-4">
          <div className="container mx-auto w-5/6">
            <div className="flex gap-6 ">
              {team}
              {dashboard}
            </div>
          </div>
        </section>
      </body>
    </html>
  );
}
